name: Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mde2-msl-test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      
      chrome:
        image: selenium/standalone-chrome:latest
        env:
          DISPLAY: :99
        ports:
          - 4444:4444
        options: >-
          --shm-size="2g"
          --add-host=host.docker.internal:host-gateway

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Selenium Dependencies
      run: |
        npm install -g selenium-side-runner@3.17.0
        npm install -g selenium-webdriver

    - name: Update Composer dependencies
      run: composer update --no-interaction --no-progress

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer dump-autoload -o

    - name: Wait for MySQL
      run: |
        for i in {30..0}; do
          if mysqladmin ping -h127.0.0.1 --silent; then
            break
          fi
          echo 'Waiting for MySQL...'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo >&2 'MySQL did not start in time.'
          exit 1
        fi

    - name: Set up database
      run: |
        mysql -h127.0.0.1 -uroot -proot_password -e "
          CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 'test_password';
          GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%';
          FLUSH PRIVILEGES;
        "

    - name: Create settings.php and run install
      run: |
        cat << EOF > settings.php
        <?php
        function connectDb() {
            \$host = '127.0.0.1';
            \$username = 'test_user';
            \$password = 'test_password';
            \$database = 'mde2-msl-test';
            \$conn = new mysqli(\$host, \$username, \$password, \$database);
            return \$conn;
        }

        function getApiKey() {
            \$apiKeyGoogleMaps = 'test_api_key';
            echo json_encode(['apiKey' => \$apiKeyGoogleMaps]);
        }

        if (basename(__FILE__) == basename(\$_SERVER['PHP_SELF'])) {
            if (\$_SERVER['REQUEST_METHOD'] === 'GET') {
                getApiKey();
            }
        }

        \$connection = connectDb();

        \$apiKeyTimezone = 'test_timezone_api_key';
        \$maxTitles = 2;
        \$mslLabsUrl = 'https://raw.githubusercontent.com/UtrechtUniversity/msl_vocabularies/main/vocabularies/labs/labnames.json';

        \$showFeedbackLink = true;
        \$smtpHost = 'smtp.test.de';
        \$smtpPort = 465;
        \$smtpUser = 'test_user';
        \$smtpPassword = 'test_password';
        \$smtpSender = 'test_sender@test.com';
        \$feedbackAdress = 'feedback@test.com';
        EOF

        php install.php

    - name: Start PHP server
      run: |
        php -S 0.0.0.0:8000 -t . > php-server.log 2>&1 &
        echo $! > php-server.pid
        
        # Wait for PHP server to be ready
        timeout=30
        until curl -s http://localhost:8000 > /dev/null || [ $timeout -eq 0 ]; do
          echo "Waiting for PHP server... ($timeout seconds left)"
          (( timeout-- ))
          sleep 1
        done
        
        if [ $timeout -eq 0 ]; then
          echo "PHP server failed to start"
          cat php-server.log
          exit 1
        fi
        
        echo "PHP server is running"
        curl -v http://localhost:8000

    - name: Run Selenium tests
      run: |
        # Check if servers are accessible
        echo "Testing PHP server:"
        curl -v http://localhost:8000
        
        echo "Testing Selenium server:"
        curl -v http://localhost:4444/wd/hub/status
        
        # Run tests
        selenium-side-runner \
          --browser chrome \
          --server http://localhost:4444/wd/hub \
          --base-url http://localhost:8000 \
          tests/Selenium/Tests_MDE.side

    - name: Stop PHP server
      if: always()
      run: |
        if [ -f php-server.pid ]; then
          kill $(cat php-server.pid) || true
        fi

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          *.log
          /var/log/apache2/*