name: Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mde2-msl-test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: >-
          --shm-size="2g"
          --health-cmd="/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Selenium Dependencies
      run: |
        npm install -g selenium-side-runner@3.17.0
        npm install -g selenium-webdriver

    - name: Update Composer dependencies
      run: composer update --no-interaction --no-progress

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer dump-autoload -o

    - name: Set up database
      run: |
        mysql -h127.0.0.1 -uroot -proot_password -e "
          CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 'test_password';
          GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%';
          FLUSH PRIVILEGES;
        "

    - name: Create settings.php
      run: |
        cat << EOF > settings.php
        <?php
        function connectDb() {
            \$host = '127.0.0.1';
            \$username = 'test_user';
            \$password = 'test_password';
            \$database = 'mde2-msl-test';
            \$conn = new mysqli(\$host, \$username, \$password, \$database);
            return \$conn;
        }

        function getApiKey() {
            \$apiKeyGoogleMaps = 'test_api_key';
            echo json_encode(['apiKey' => \$apiKeyGoogleMaps]);
        }

        if (basename(__FILE__) == basename(\$_SERVER['PHP_SELF'])) {
            if (\$_SERVER['REQUEST_METHOD'] === 'GET') {
                getApiKey();
            }
        }

        \$connection = connectDb();

        \$apiKeyTimezone = 'test_timezone_api_key';
        \$maxTitles = 2;
        \$mslLabsUrl = 'https://raw.githubusercontent.com/UtrechtUniversity/msl_vocabularies/main/vocabularies/labs/labnames.json';

        \$showFeedbackLink = true;
        \$smtpHost = 'smtp.test.de';
        \$smtpPort = 465;
        \$smtpUser = 'test_user';
        \$smtpPassword = 'test_password';
        \$smtpSender = 'test_sender@test.com';
        \$feedbackAdress = 'feedback@test.com';
        EOF

    - name: Run install.php
      run: php install.php

    - name: Start PHP server
      run: |
        # Start PHP server
        php -S 0.0.0.0:8000 -t . > php-server.log 2>&1 &
        echo $! > php-server.pid
        
        # Wait for PHP server to be ready
        max_attempts=30
        attempt=1
        echo "Waiting for PHP server to be ready..."
        while [ $attempt -le $max_attempts ]; do
          if curl -s http://localhost:8000 > /dev/null; then
            echo "PHP server is ready!"
            break
          fi
          echo "Attempt $attempt of $max_attempts"
          sleep 1
          attempt=$((attempt + 1))
        done
        
        if [ $attempt -gt $max_attempts ]; then
          echo "PHP server failed to start"
          cat php-server.log
          exit 1
        fi

    - name: Wait for Selenium
      run: |
        echo "Waiting for Selenium..."
        timeout=30
        while [ $timeout -gt 0 ]; do
          if curl -sSL "http://localhost:4444/wd/hub/status" | grep -q "ready.*true"; then
            echo "Selenium is ready"
            break
          fi
          echo "Waiting... ($timeout seconds left)"
          sleep 1
          timeout=$((timeout-1))
        done
        
        if [ $timeout -eq 0 ]; then
          echo "Selenium failed to start"
          exit 1
        fi

    - name: Run Selenium tests
      run: |
        # Create selenium config file
        cat << EOF > selenium.json
        {
          "capabilities": {
            "browserName": "chrome",
            "goog:chromeOptions": {
              "args": ["--no-sandbox", "--headless", "--disable-gpu", "--disable-dev-shm-usage"]
            }
          }
        }
        EOF
        
        selenium-side-runner \
          -c selenium.json \
          --server http://localhost:4444/wd/hub \
          --base-url http://localhost:8000 \
          --timeout 30000 \
          tests/Selenium/Tests_MDE.side

    - name: Show logs on failure
      if: failure()
      run: |
        echo "PHP Server Log:"
        cat php-server.log || true
        echo "Selenium container logs:"
        docker logs $(docker ps -qf "name=selenium") || true

    - name: Stop PHP server
      if: always()
      run: |
        if [ -f php-server.pid ]; then
          kill $(cat php-server.pid) || true
        fi

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          *.log
          selenium.json