name: Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mde2-msl-test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Selenium Dependencies
      run: |
        npm install -g selenium-side-runner@3.17.0
        npm install -g selenium-webdriver

    - name: Update Composer dependencies
      run: composer update --no-interaction --no-progress

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer dump-autoload -o

    - name: Set up database
      run: |
        mysql -h127.0.0.1 -uroot -proot_password -e "
          CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 'test_password';
          GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%';
          FLUSH PRIVILEGES;
        "

    - name: Create settings.php
      run: |
        cat << EOF > settings.php
        <?php
        function connectDb() {
            \$host = '127.0.0.1';
            \$username = 'test_user';
            \$password = 'test_password';
            \$database = 'mde2-msl-test';
            \$conn = new mysqli(\$host, \$username, \$password, \$database);
            return \$conn;
        }

        function getApiKey() {
            \$apiKeyGoogleMaps = 'test_api_key';
            echo json_encode(['apiKey' => \$apiKeyGoogleMaps]);
        }

        if (basename(__FILE__) == basename(\$_SERVER['PHP_SELF'])) {
            if (\$_SERVER['REQUEST_METHOD'] === 'GET') {
                getApiKey();
            }
        }

        \$connection = connectDb();

        \$apiKeyTimezone = 'test_timezone_api_key';
        \$maxTitles = 2;
        \$mslLabsUrl = 'https://raw.githubusercontent.com/UtrechtUniversity/msl_vocabularies/main/vocabularies/labs/labnames.json';

        \$showFeedbackLink = true;
        \$smtpHost = 'smtp.test.de';
        \$smtpPort = 465;
        \$smtpUser = 'test_user';
        \$smtpPassword = 'test_password';
        \$smtpSender = 'test_sender@test.com';
        \$feedbackAdress = 'feedback@test.com';
        EOF

    - name: Run install.php
      run: php install.php

    - name: Create Docker network
      run: docker network create test-network

    - name: Start Selenium container
      run: |
        docker run -d --network test-network \
          --name selenium \
          -p 4444:4444 \
          -p 7900:7900 \
          --shm-size="2g" \
          selenium/standalone-chrome:latest

    - name: Start PHP server
      run: |
        docker run -d --network test-network \
          --name php-app \
          -v ${{ github.workspace }}:/var/www/html \
          -p 8000:8000 \
          php:8.2-cli \
          php -S 0.0.0.0:8000 -t /var/www/html

    - name: Wait for services
      run: |
        # Wait for Selenium
        timeout=30
        until curl -s http://localhost:4444/wd/hub/status > /dev/null; do
          if [ $timeout -eq 0 ]; then
            echo "Selenium failed to start"
            exit 1
          fi
          echo "Waiting for Selenium... ($timeout seconds left)"
          timeout=$((timeout-1))
          sleep 1
        done

        # Wait for PHP
        timeout=30
        until curl -s http://localhost:8000 > /dev/null; do
          if [ $timeout -eq 0 ]; then
            echo "PHP server failed to start"
            exit 1
          fi
          echo "Waiting for PHP server... ($timeout seconds left)"
          timeout=$((timeout-1))
          sleep 1
        done

    - name: Run Selenium tests
      run: |
        selenium-side-runner \
          --browser chrome \
          --server http://localhost:4444/wd/hub \
          --base-url http://php-app:8000 \
          tests/Selenium/Tests_MDE.side

    - name: Cleanup
      if: always()
      run: |
        docker stop selenium php-app || true
        docker rm selenium php-app || true
        docker network rm test-network || true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          *.log
          /var/log/apache2/*